# Generated by Django 6.0.5 on 2026-06-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motostore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='casco',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motocicleta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
